import type { DifficultyLevel } from "@/game/types";

/**
 * Actions the UI dispatches into the game engine. These never touch the
 * network directly — the engine decides what (if anything) needs to be
 * sent to the peer as a result, see `game/engine/engine.ts`.
 */
export type LocalAction =
  /**
   * Host only — picks how many characters are in play. `characterIds` is
   * the random draw itself (see `data/difficulty.ts`'s
   * `pickRandomCharacterIds`), generated by the caller (hook layer) so the
   * engine stays a pure, sync function — same pattern as `salt` below.
   */
  | { type: "SET_DIFFICULTY"; level: DifficultyLevel; characterIds: string[] }
  | { type: "SET_READY" }
  /** `salt` is generated by the caller (hook layer) so the engine stays a pure, sync function. */
  | { type: "SELECT_CHARACTER"; characterId: string; salt: string }
  /**
   * Questions and answers happen out loud between the two players (see
   * CLAUDE.md) — the app has no ASK_QUESTION/ANSWER action. Once a player
   * is done asking (and hearing the answer) verbally, they self-report
   * that their turn is over.
   */
  | { type: "END_TURN" }
  /** Local-only bookkeeping: cross a character off MY OWN board. Never sent over the network. */
  | { type: "ELIMINATE_CHARACTER"; characterId: string }
  | { type: "RESTORE_CHARACTER"; characterId: string }
  | { type: "GUESS_CHARACTER"; characterId: string }
  | { type: "RESTART" }
  /** Fired by the connection layer once the DataChannel is open and HELLO can be sent. */
  | { type: "CONNECTION_ESTABLISHED"; localName: string }
  /** Player edits their own display name after already connecting (e.g. from the connected screen). */
  | { type: "SET_NAME"; name: string }
  /** Fired by the connection layer if the peer disconnects mid-game (forfeit-by-disconnect). */
  | { type: "OPPONENT_DISCONNECTED" };

export type LocalActionType = LocalAction["type"];
